## **Plotly - 01**

In [ ]:
# install plotly
# install kaleido
# check other modules also

In [1]:
# import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [ ]:
# line chart 
#px.line(x,y,title)
names= ["Hammad","Huzaifa","Ammar"]
heights = [5.7,5.8,5.9]

fig = px.line(x=names,y=heights,title="Height of Students",)
fig.show()

In [ ]:
# bar --> px.bar()
# fig.show()
students= ["huzaifa","haider","hammad"]
candies = [19,7,2]

fig = px.bar(x= students, y= candies,title="No.of Candies Got Each Student")
fig.show()

In [ ]:
# save the plot in png file ---> fig.write_image(path + name, format, scale)
x= np.linspace(-10,10,20)
y= np.linspace(-10,5,20)

fig = px.line(x,y)
# save in 300 DPI ( Dots Per Inch) scale = 3

fig.write_image("Line Chart in Plotly", format="png", scale=3) # only be done when kaleido is installed

In [12]:
# save as standalone html file ---> fig.write_html()
x= np.linspace(-10,10,20)
y= np.linspace(-10,5,20)

fig = px.line(x,y)
fig.write_html("Line Chart in Plotly.html")

In [14]:
# on dataset
df = pd.read_csv(r"titanic.csv")
df.dropna(inplace = True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
# scatter plot ---> df, x, y, color, size etc....
fig = px.scatter(df,x ="Age",y="Fare", color = "Sex",size="Fare")

fig.write_html("Scatter Plot")

In [ ]:
# go ---> go.Figure( data = ) ---> Figure Class
import plotly.graph_objects as go
fig = go.Figure(data = go.Scatter(x=[1,2,3,4], y= [9,8,7,6]))
fig.show()

In [ ]:
# fig.update_layout() --> all properties
# autosize
#             Determines whether or not a layout width or height that
#             has been left undefined by the user is initialized on
#             each relayout. Note that, regardless of this attribute,
#             an undefined layout width or height is always
#             initialized on the first call to plot.
#         autotypenumbers
#             Using "strict" a numeric string in trace data is not
#             converted to a number. Using *convert types* a numeric
#             string in trace data may be treated as a number during
#             automatic axis `type` detection. This is the default
#             value; however it could be overridden for individual
#             axes.
#         barcornerradius
#             Sets the rounding of bar corners. May be an integer
#             number of pixels, or a percentage of bar width (as a
#             string ending in %).
#         bargap
#             Sets the gap (in plot fraction) between bars of
#             adjacent location coordinates.
#         bargroupgap
#             Sets the gap (in plot fraction) between bars of the
#             same location coordinate.
#         barmode
#             Determines how bars at the same location coordinate are
#             displayed on the graph. With "stack", the bars are
#             stacked on top of one another With "relative", the bars
#             are stacked on top of one another, with negative values
#             below the axis, positive values above With "group", the
#             bars are plotted next to one another centered around
#             the shared location. With "overlay", the bars are
#             plotted over one another, you might need to reduce
#             "opacity" to see multiple bars.
#         barnorm
#             Sets the normalization for bar traces on the graph.
#             With "fraction", the value of each bar is divided by
#             the sum of all values at that location coordinate.
#             "percent" is the same but multiplied by 100 to show
#             percentages.
#         boxgap
#             Sets the gap (in plot fraction) between boxes of
#             adjacent location coordinates. Has no effect on traces
#             that have "width" set.
#         boxgroupgap
#             Sets the gap (in plot fraction) between boxes of the
#             same location coordinate. Has no effect on traces that
#             have "width" set.
#         boxmode
#             Determines how boxes at the same location coordinate
#             are displayed on the graph. If "group", the boxes are
#             plotted next to one another centered around the shared
#             location. If "overlay", the boxes are plotted over one
#             another, you might need to set "opacity" to see them
#             multiple boxes. Has no effect on traces that have
#             "width" set.
#         calendar
#             Sets the default calendar system to use for
#             interpreting and displaying dates throughout the plot.
#         clickanywhere
#             If true, `plotly_click` events will fire for any click
#             position within the plot area, not just over traces.
#             When clicking where there is no trace data, the event
#             will have an empty `points` array but will include
#             `xvals` and `yvals` with click coordinates in data
#             space.
#         clickmode
#             Determines the mode of single click interactions.
#             "event" is the default value and emits the
#             `plotly_click` event. In addition this mode emits the
#             `plotly_selected` event in drag modes "lasso" and
#             "select", but with no event data attached (kept for
#             compatibility reasons). The "select" flag enables
#             selecting single data points via click. This mode also
#             supports persistent selections, meaning that pressing
#             Shift while clicking, adds to / subtracts from an
#             existing selection. "select" with `hovermode`: "x" can
#             be confusing, consider explicitly setting `hovermode`:
#             "closest" when using this feature. Selection events are
#             sent accordingly as long as "event" flag is set as
#             well. When the "event" flag is missing, `plotly_click`
#             and `plotly_selected` events are not fired.
#         coloraxis
#             :class:`plotly.graph_objects.layout.Coloraxis` instance
#             or dict with compatible properties
#         colorscale
#             :class:`plotly.graph_objects.layout.Colorscale`
#             instance or dict with compatible properties
#         colorway
#             Sets the default trace colors.
#         computed
#             Placeholder for exporting automargin-impacting values
#             namely `margin.t`, `margin.b`, `margin.l` and
#             `margin.r` in "full-json" mode.
#         datarevision
#             If provided, a changed value tells `Plotly.react` that
#             one or more data arrays has changed. This way you can
#             modify arrays in-place rather than making a complete
#             new copy for an incremental change. If NOT provided,
#             `Plotly.react` assumes that data arrays are being
#             treated as immutable, thus any data array with a
#             different identity from its predecessor contains new
#             data.
#         dragmode
#             Determines the mode of drag interactions. "select" and
#             "lasso" apply only to scatter traces with markers or
#             text. "orbit" and "turntable" apply only to 3D scenes.
#         editrevision
#             Controls persistence of user-driven changes in
#             `editable: true` configuration, other than trace names
#             and axis titles. Defaults to `layout.uirevision`.
#         extendfunnelareacolors
#             If `true`, the funnelarea slice colors (whether given
#             by `funnelareacolorway` or inherited from `colorway`)
#             will be extended to three times its original length by
#             first repeating every color 20% lighter then each color
#             20% darker. This is intended to reduce the likelihood
#             of reusing the same color when you have many slices,
#             but you can set `false` to disable. Colors provided in
#             the trace, using `marker.colors`, are never extended.
#         extendiciclecolors
#             If `true`, the icicle slice colors (whether given by
#             `iciclecolorway` or inherited from `colorway`) will be
#             extended to three times its original length by first
#             repeating every color 20% lighter then each color 20%
#             darker. This is intended to reduce the likelihood of
#             reusing the same color when you have many slices, but
#             you can set `false` to disable. Colors provided in the
#             trace, using `marker.colors`, are never extended.
#         extendpiecolors
#             If `true`, the pie slice colors (whether given by
#             `piecolorway` or inherited from `colorway`) will be
#             extended to three times its original length by first
#             repeating every color 20% lighter then each color 20%
#             darker. This is intended to reduce the likelihood of
#             reusing the same color when you have many slices, but
#             you can set `false` to disable. Colors provided in the
#             trace, using `marker.colors`, are never extended.
#         extendsunburstcolors
#             If `true`, the sunburst slice colors (whether given by
#             `sunburstcolorway` or inherited from `colorway`) will
#             be extended to three times its original length by first
#             repeating every color 20% lighter then each color 20%
#             darker. This is intended to reduce the likelihood of
#             reusing the same color when you have many slices, but
#             you can set `false` to disable. Colors provided in the
#             trace, using `marker.colors`, are never extended.
#         extendtreemapcolors
#             If `true`, the treemap slice colors (whether given by
#             `treemapcolorway` or inherited from `colorway`) will be
#             extended to three times its original length by first
#             repeating every color 20% lighter then each color 20%
#             darker. This is intended to reduce the likelihood of
#             reusing the same color when you have many slices, but
#             you can set `false` to disable. Colors provided in the
#             trace, using `marker.colors`, are never extended.
#         font
#             Sets the global font. Note that fonts used in traces
#             and other layout components inherit from the global
#             font.
#         funnelareacolorway
#             Sets the default funnelarea slice colors. Defaults to
#             the main `colorway` used for trace colors. If you
#             specify a new list here it can still be extended with
#             lighter and darker colors, see
#             `extendfunnelareacolors`.
#         funnelgap
#             Sets the gap (in plot fraction) between bars of
#             adjacent location coordinates.
#         funnelgroupgap
#             Sets the gap (in plot fraction) between bars of the
#             same location coordinate.
#         funnelmode
#             Determines how bars at the same location coordinate are
#             displayed on the graph. With "stack", the bars are
#             stacked on top of one another With "group", the bars
#             are plotted next to one another centered around the
#             shared location. With "overlay", the bars are plotted
#             over one another, you might need to reduce "opacity" to
#             see multiple bars.
#         geo
#             :class:`plotly.graph_objects.layout.Geo` instance or
#             dict with compatible properties
#         grid
#             :class:`plotly.graph_objects.layout.Grid` instance or
#             dict with compatible properties
#         height
#             Sets the plot's height (in px).
#         hiddenlabels
#             hiddenlabels is the funnelarea & pie chart analog of
#             visible:'legendonly' but it can contain many labels,
#             and can simultaneously hide slices from several
#             pies/funnelarea charts
#         hiddenlabelssrc
#             Sets the source reference on Chart Studio Cloud for
#             `hiddenlabels`.
#         hidesources
#             Determines whether or not a text link citing the data
#             source is placed at the bottom-right cored of the
#             figure. Has only an effect only on graphs that have
#             been generated via forked graphs from the Chart Studio
#             Cloud (at https://chart-studio.plotly.com or on-
#             premise).
#         hoveranywhere
#             If true, `plotly_hover` events will fire for any cursor
#             position within the plot area, not just over traces.
#             When the cursor is not over a trace, the event will
#             have an empty `points` array but will include `xvals`
#             and `yvals` with cursor coordinates in data space.
#         hoverdistance
#             Sets the default distance (in pixels) to look for data
#             to add hover labels (-1 means no cutoff, 0 means no
#             looking for data). This is only a real distance for
#             hovering on point-like objects, like scatter points.
#             For area-like objects (bars, scatter fills, etc)
#             hovering is on inside the area and off outside, but
#             these objects will not supersede hover on point-like
#             objects in case of conflict.
#         hoverlabel
#             :class:`plotly.graph_objects.layout.Hoverlabel`
#             instance or dict with compatible properties
#         hovermode
#             Determines the mode of hover interactions. If
#             "closest", a single hoverlabel will appear for the
#             "closest" point within the `hoverdistance`. If "x" (or
#             "y"), multiple hoverlabels will appear for multiple
#             points at the "closest" x- (or y-) coordinate within
#             the `hoverdistance`, with the caveat that no more than
#             one hoverlabel will appear per trace. If *x unified*
#             (or *y unified*), a single hoverlabel will appear
#             multiple points at the closest x- (or y-) coordinate
#             within the `hoverdistance` with the caveat that no more
#             than one hoverlabel will appear per trace. In this
#             mode, spikelines are enabled by default perpendicular
#             to the specified axis. If false, hover interactions are
#             disabled.
#         hoversort
#             Determines the order of items shown in unified hover
#             labels. If "trace", items are sorted by trace index. If
#             *value descending*, items are sorted by value from
#             largest to smallest. If *value ascending*, items are
#             sorted by value from smallest to largest. Only applies
#             when `hovermode` is *x unified* or *y unified*.
#         hoversubplots
#             Determines expansion of hover effects to other subplots
#             If "single" just the axis pair of the primary point is
#             included without overlaying subplots. If "overlaying"
#             all subplots using the main axis and occupying the same
#             space are included. If "axis", also include stacked
#             subplots using the same axis when `hovermode` is set to
#             "x", *x unified*, "y" or *y unified*.
#         iciclecolorway
#             Sets the default icicle slice colors. Defaults to the
#             main `colorway` used for trace colors. If you specify a
#             new list here it can still be extended with lighter and
#             darker colors, see `extendiciclecolors`.
#         images
#             A tuple of :class:`plotly.graph_objects.layout.Image`
#             instances or dicts with compatible properties
#         imagedefaults
#             When used in a template (as
#             layout.template.layout.imagedefaults), sets the default
#             property values to use for elements of layout.images
#         legend
#             :class:`plotly.graph_objects.layout.Legend` instance or
#             dict with compatible properties
#         map
#             :class:`plotly.graph_objects.layout.Map` instance or
#             dict with compatible properties
#         mapbox
#             :class:`plotly.graph_objects.layout.Mapbox` instance or
#             dict with compatible properties
#         margin
#             :class:`plotly.graph_objects.layout.Margin` instance or
#             dict with compatible properties
#         meta
#             Assigns extra meta information that can be used in
#             various `text` attributes. Attributes such as the
#             graph, axis and colorbar `title.text`, annotation
#             `text` `trace.name` in legend items, `rangeselector`,
#             `updatemenus` and `sliders` `label` text all support
#             `meta`. One can access `meta` fields using template
#             strings: `%{meta[i]}` where `i` is the index of the
#             `meta` item in question. `meta` can also be an object
#             for example `{key: value}` which can be accessed
#             %{meta[key]}.
#         metasrc
#             Sets the source reference on Chart Studio Cloud for
#             `meta`.
#         minreducedheight
#             Minimum height of the plot with margin.automargin
#             applied (in px)
#         minreducedwidth
#             Minimum width of the plot with margin.automargin
#             applied (in px)
#         modebar
#             :class:`plotly.graph_objects.layout.Modebar` instance
#             or dict with compatible properties
#         newselection
#             :class:`plotly.graph_objects.layout.Newselection`
#             instance or dict with compatible properties
#         newshape
#             :class:`plotly.graph_objects.layout.Newshape` instance
#             or dict with compatible properties
#         paper_bgcolor
#             Sets the background color of the paper where the graph
#             is drawn.
#         piecolorway
#             Sets the default pie slice colors. Defaults to the main
#             `colorway` used for trace colors. If you specify a new
#             list here it can still be extended with lighter and
#             darker colors, see `extendpiecolors`.
#         plot_bgcolor
#             Sets the background color of the plotting area in-
#             between x and y axes.
#         polar
#             :class:`plotly.graph_objects.layout.Polar` instance or
#             dict with compatible properties
#         scattergap
#             Sets the gap (in plot fraction) between scatter points
#             of adjacent location coordinates. Defaults to `bargap`.
#         scattermode
#             Determines how scatter points at the same location
#             coordinate are displayed on the graph. With "group",
#             the scatter points are plotted next to one another
#             centered around the shared location. With "overlay",
#             the scatter points are plotted over one another, you
#             might need to reduce "opacity" to see multiple scatter
#             points.
#         scene
#             :class:`plotly.graph_objects.layout.Scene` instance or
#             dict with compatible properties
#         selectdirection
#             When `dragmode` is set to "select", this limits the
#             selection of the drag to horizontal, vertical or
#             diagonal. "h" only allows horizontal selection, "v"
#             only vertical, "d" only diagonal and "any" sets no
#             limit.
#         selectionrevision
#             Controls persistence of user-driven changes in selected
#             points from all traces.
#         selections
#             A tuple of
#             :class:`plotly.graph_objects.layout.Selection`
#             instances or dicts with compatible properties
#         selectiondefaults
#             When used in a template (as
#             layout.template.layout.selectiondefaults), sets the
#             default property values to use for elements of
#             layout.selections
#         separators
#             Sets the decimal and thousand separators. For example,
#             *. * puts a '.' before decimals and a space between
#             thousands. In English locales, dflt is ".," but other
#             locales may alter this default.
#         shapes
#             A tuple of :class:`plotly.graph_objects.layout.Shape`
#             instances or dicts with compatible properties
#         shapedefaults
#             When used in a template (as
#             layout.template.layout.shapedefaults), sets the default
#             property values to use for elements of layout.shapes
#         showlegend
#             Determines whether or not a legend is drawn. Default is
#             `true` if there is a trace to show and any of these: a)
#             Two or more traces would by default be shown in the
#             legend. b) One pie trace is shown in the legend. c) One
#             trace is explicitly given with `showlegend: true`.
#         sliders
#             A tuple of :class:`plotly.graph_objects.layout.Slider`
#             instances or dicts with compatible properties
#         sliderdefaults
#             When used in a template (as
#             layout.template.layout.sliderdefaults), sets the
#             default property values to use for elements of
#             layout.sliders
#         smith
#             :class:`plotly.graph_objects.layout.Smith` instance or
#             dict with compatible properties
#         spikedistance
#             Sets the default distance (in pixels) to look for data
#             to draw spikelines to (-1 means no cutoff, 0 means no
#             looking for data). As with hoverdistance, distance does
#             not apply to area-like objects. In addition, some
#             objects can be hovered on but will not generate
#             spikelines, such as scatter fills.
#         sunburstcolorway
#             Sets the default sunburst slice colors. Defaults to the
#             main `colorway` used for trace colors. If you specify a
#             new list here it can still be extended with lighter and
#             darker colors, see `extendsunburstcolors`.
#         template
#             Default attributes to be applied to the plot. This
#             should be a dict with format: `{'layout':
#             layoutTemplate, 'data': {trace_type: [traceTemplate,
#             ...], ...}}` where `layoutTemplate` is a dict matching
#             the structure of `figure.layout` and `traceTemplate` is
#             a dict matching the structure of the trace with type
#             `trace_type` (e.g. 'scatter'). Alternatively, this may
#             be specified as an instance of
#             plotly.graph_objs.layout.Template.  Trace templates are
#             applied cyclically to traces of each type. Container
#             arrays (eg `annotations`) have special handling: An
#             object ending in `defaults` (eg `annotationdefaults`)
#             is applied to each array item. But if an item has a
#             `templateitemname` key we look in the template array
#             for an item with matching `name` and apply that
#             instead. If no matching `name` is found we mark the
#             item invisible. Any named template item not referenced
#             is appended to the end of the array, so this can be
#             used to add a watermark annotation or a logo image, for
#             example. To omit one of these items on the plot, make
#             an item with matching `templateitemname` and `visible:
#             false`.
#         ternary
#             :class:`plotly.graph_objects.layout.Ternary` instance
#             or dict with compatible properties
#         title
#             :class:`plotly.graph_objects.layout.Title` instance or
#             dict with compatible properties
#         transition
#             Sets transition options used during Plotly.react
#             updates.
#         treemapcolorway
#             Sets the default treemap slice colors. Defaults to the
#             main `colorway` used for trace colors. If you specify a
#             new list here it can still be extended with lighter and
#             darker colors, see `extendtreemapcolors`.
#         uirevision
#             Used to allow user interactions with the plot to
#             persist after `Plotly.react` calls that are unaware of
#             these interactions. If `uirevision` is omitted, or if
#             it is given and it changed from the previous
#             `Plotly.react` call, the exact new figure is used. If
#             `uirevision` is truthy and did NOT change, any
#             attribute that has been affected by user interactions
#             and did not receive a different value in the new figure
#             will keep the interaction value. `layout.uirevision`
#             attribute serves as the default for `uirevision`
#             attributes in various sub-containers. For finer control
#             you can set these sub-attributes directly. For example,
#             if your app separately controls the data on the x and y
#             axes you might set `xaxis.uirevision=*time*` and
#             `yaxis.uirevision=*cost*`. Then if only the y data is
#             changed, you can update `yaxis.uirevision=*quantity*`
#             and the y axis range will reset but the x axis range
#             will retain any user-driven zoom.
#         uniformtext
#             :class:`plotly.graph_objects.layout.Uniformtext`
#             instance or dict with compatible properties
#         updatemenus
#             A tuple of
#             :class:`plotly.graph_objects.layout.Updatemenu`
#             instances or dicts with compatible properties
#         updatemenudefaults
#             When used in a template (as
#             layout.template.layout.updatemenudefaults), sets the
#             default property values to use for elements of
#             layout.updatemenus
#         violingap
#             Sets the gap (in plot fraction) between violins of
#             adjacent location coordinates. Has no effect on traces
#             that have "width" set.
#         violingroupgap
#             Sets the gap (in plot fraction) between violins of the
#             same location coordinate. Has no effect on traces that
#             have "width" set.
#         violinmode
#             Determines how violins at the same location coordinate
#             are displayed on the graph. If "group", the violins are
#             plotted next to one another centered around the shared
#             location. If "overlay", the violins are plotted over
#             one another, you might need to set "opacity" to see
#             them multiple violins. Has no effect on traces that
#             have "width" set.
#         waterfallgap
#             Sets the gap (in plot fraction) between bars of
#             adjacent location coordinates.
#         waterfallgroupgap
#             Sets the gap (in plot fraction) between bars of the
#             same location coordinate.
#         waterfallmode
#             Determines how bars at the same location coordinate are
#             displayed on the graph. With "group", the bars are
#             plotted next to one another centered around the shared
#             location. With "overlay", the bars are plotted over one
#             another, you might need to reduce "opacity" to see
#             multiple bars.
#         width
#             Sets the plot's width (in px).
#         xaxis
#             :class:`plotly.graph_objects.layout.XAxis` instance or
#             dict with compatible properties
#         yaxis
#             :class:`plotly.graph_objects.layout.YAxis` instan

In [30]:
# fig.update_layout ---> pass all properties in a dictionary and some properties also have a dictionary to provide more values
#title,xaxis, yaxis, show legend,
fig.update_layout({ 
  "title":"Graph Using Graph Objects of Plotly",
  "xaxis": {"title":"Numbers"},
  "yaxis": {"title": "Values"},
  "showlegend": True
})
fig.show()

In [ ]:
#go on data set ---> creating simple line chart using go.Scatter class
fig = go.Figure(data = go.Scatter(x=df["Age"], y= df["Fare"]))
fig.show()

## Heatmaps

In [51]:
import plotly.graph_objects as go
# go.Heatmap(z= data_for heatmap) this Class object is used to make Heatmap of the data.

data = np.random.rand(10,10)

pd.DataFrame(data)

,0,1,2,3,4,5,6,7,8,9
0,0.355113,0.751930,0.147097,0.081297,0.634527,0.168632,0.122384,0.738264,0.716086,0.710009
1,0.042041,0.596762,0.708770,0.403853,0.641261,0.004497,0.855365,0.579338,0.596912,0.173365
2,0.812459,0.423328,0.467386,0.296043,0.390283,0.870061,0.814326,0.003744,0.651495,0.414639
3,0.832703,0.300598,0.556197,0.997027,0.525547,0.267172,0.630025,0.656189,0.172879,0.442352
4,0.830120,0.236962,0.284996,0.143295,0.632535,0.080700,0.537318,0.732376,0.123894,0.777776
5,0.392181,0.584905,0.044702,0.623275,0.362963,0.640601,0.490733,0.489616,0.202175,0.294704
6,0.389253,0.710715,0.080440,0.410688,0.402214,0.934338,0.666797,0.610946,0.620078,0.707275
7,0.640539,0.535018,0.207416,0.559337,0.952226,0.116749,0.479747,0.063377,0.171629,0.407389
8,0.307433,0.207557,0.086276,0.190245,0.585412,0.097266,0.112088,0.893908,0.957716,0.768878
9,0.423656,0.124084,0.270291,0.856035,0.629771,0.775691,0.718703,0.221691,0.965444,0.723330

In [ ]:
# Heatmap of the Data




heatmap = go.Heatmap(z=data) # z parameter

# heatmap is the object of the class go.Heatmap(data)
# using this ( heatmap ) object  in the go.Figure class  we make another object (fig)  that object is heatmap.

fig = go.Figure(data=heatmap)
fig.show()

In [ ]:
# Heatmap on correlation corr of titanic dataset of age and fare using plotly
# using px.imshow() method
# 1st method
data = df[["Age","Fare"]].corr()
fig = px.imshow(data)
fig.show()

In [ ]:
# nticks --> x,yaxis
# size of plot using width and height in dictionary

data = df[["Age","Fare"]].corr()
heatmap = go.Heatmap(z=data)
fig = go.Figure(heatmap)
fig.update_layout(
  {
    "title": "Correlation between Age & Fare",
    "xaxis" : {"title": "Age","nticks": 50},
    "yaxis": {"title": "Fare","nticks":50},
    "width": 1000,
    "height": 800
  }
)

In [86]:
# on Iris Data set
iris = pd.read_csv(r"C:\Hammad Mustafa\A Long Journey\AI\Artificial Intelligence (AI)\Data Science (Machine Learning) Libraries\Plotly\iris.csv")
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [90]:
fig = px.imshow(iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].corr())
fig.show()